// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmsdcWebApi.Model;

#nullable disable

namespace SmsdcWebApi.Migrations
{
    [DbContext(typeof(SmsdcContext))]
    partial class SmsdcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmsdcWebApi.Model.Ba", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherIncome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherOccupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HighSchoolPassDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HighSchoolRollNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject1Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject2Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject3Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject4Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject5Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject6Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject7Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolTotalPercentage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("IntermediatePassDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IntermediateRollNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject1Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject2Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject3Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject4Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject5Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject6Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject7Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateTotalPercentage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherIncome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherOccupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semester")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BaStudents");
                });

            modelBuilder.Entity("SmsdcWebApi.Model.Bsc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherIncome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherOccupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GraduationCollegeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GraduationCourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GraduationPassYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("GraduationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HighSchoolPassDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HighSchoolRollNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject1Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject2Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject3Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject4Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject5Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject6Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolSubject7Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighSchoolTotalPercentage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("IntermediatePassDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IntermediateRollNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject1Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject2Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject3Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject4Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject5Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject6Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateSubject7Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediateTotalPercentage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherIncome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherOccupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semester")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BscStudents");
                });

            modelBuilder.Entity("SmsdcWebApi.Model.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("SmsdcWebApi.Model.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("States");
                });
#pragma warning restore 612, 618
        }
    }
}
